### ISSUE TITLE
请问KMS端口1688能用nginx代理吗

### ISSUE THREAD

**Issue by walirt** [dnomd343/kms-server#3]

**Comment by dnomd343** [comment]
可以的，但KMS不是http协议，需要用nginx代理原始TCP连接，即stream模块，不过这个场景下反向代理的意义貌似不大？

**Comment by walirt** [comment]
> 可以的，但KMS不是http协议，需要用nginx代理原始TCP连接，即stream模块，不过这个场景下反向代理的意义貌似不大？

嗯 已经用stream模块解决了
